### ISSUE TITLE
Lot of problems under Xubuntu 20.04 final

### ISSUE THREAD

**Issue by ale5000-git** [B00merang-Project/Windows-7#2] opened 2020-04-07 05:14 UTC
First, thanks for the theme :)

I have some problems:
1) ~~Background color of start menu icon wrong when menu is open and closed~~ Fixed
2) ~~Background color of system tray icons wrong~~ Fixed
3) ~~Background color of date/time icon wrong~~ Fixed
4) ~~The color of the text of desktop icons is wrong~~ Fixed
5) ~~Strange text shadow on systray icons~~ Fixed
6) ~~Title bar of most apps is not changed~~ Fixed

7) The background color of the pinned apps is wrong.
Here how it look now:
![win7-theme](https://user-images.githubusercontent.com/15793015/80052395-e2446b00-851a-11ea-8375-5eea0a6c2b41.png)
Compared to default theme:
![xubuntu-theme](https://user-images.githubusercontent.com/15793015/80052417-eb353c80-851a-11ea-97bb-d28d3122146c.png)

9) There are also strange vertical white bars near the notification icon.

**Comment by Elbullazul** [comment] 2020-04-09 17:17
will have a look at this when I have time, possibly in two weeks. Sorry for the delay

**Comment by ale5000-git** [comment] 2020-04-09 19:21
Ok, thanks :)

**Comment by Elbullazul** [comment] 2020-04-23 00:57
menu background is feasible but impractical at the moment. Menu button can be manually changed

> Background of system tray icons wrong
> Background of date/time icon wrong

have been fixed.

**Comment by ale5000-git** [comment] 2020-04-23 02:20
Thanks for the fixes, with "menu background" I was meaning the background color of the menu icon that is now fixed but now that you say it also the background of the entire menu need to be fixed but I think it is the less important.

About the menu button, in the screenschot [here](https://b00merang.weebly.com/windows-7.html) it appears to be changed, isn't possible to do it automatically with maybe the icon theme?

**Comment by ale5000-git** [comment] 2020-04-23 02:30
Here how it look now:
![win7-theme](https://user-images.githubusercontent.com/15793015/80052395-e2446b00-851a-11ea-8375-5eea0a6c2b41.png)

Compared to default theme:
![xubuntu-theme](https://user-images.githubusercontent.com/15793015/80052417-eb353c80-851a-11ea-97bb-d28d3122146c.png)

How you can see it is mostly ok but the background color of the pinned apps is wrong.
Also if possible it would be nice if the pinned apps are positioned near the start menu and not near date/time.

**Comment by ale5000-git** [comment] 2020-04-23 03:09
12) Also anothe issue:
![win7-theme-icon-menu](https://user-images.githubusercontent.com/15793015/80054844-9e546480-8520-11ea-82d2-373bcf05479c.png)

On default theme it look like this:
![xubuntu-theme-icon-menu](https://user-images.githubusercontent.com/15793015/80054861-a90ef980-8520-11ea-807d-41b0f582f272.png)

**Comment by Elbullazul** [comment] 2020-04-23 12:55
> How you can see it is mostly ok but the background color of the pinned apps is wrong.

noted.

> Also if possible it would be nice if the pinned apps are positioned near the start menu and not near date/time.

that"s the panel's layout and has to be manually edited. Themes can't change that

> There are also strange vertical white bars near the notification icon.

It seems to be a necessary compromise for a transparent panel, but I'll try exploring other solutions

**Comment by Elbullazul** [comment] 2020-04-23 13:18
The menu issue is on the todo list, possibly fixed today

**Comment by ale5000-git** [comment] 2020-04-23 15:48
> that's how it is, thunar doesn't have the same layout as Windows Explorer ¯_(ツ)_/¯

It doesn't need to be exactly equal but why the back, forward, up and the refresh buttons aren't changed like in Windows 7?

About the desktop labels color I will try.

**Comment by Elbullazul** [comment] 2020-04-30 13:15
> It doesn't need to be exactly equal but why the back, forward, up and the refresh buttons aren't changed like in Windows 7?

because I haven't bothered implementing it. It's technically possible, but IMO it's not worth to develop a feature for one single program.

also, last time I checked, the icon theme was supposed to have special icons for back, forward and up buttons.

but if I find time, I can try to make something similar to the original

**Comment by Elbullazul** [comment] 2020-11-12 03:27
found a correction for the desktop text color, fix coming in the following weeks

**Comment by Elbullazul** [comment] 2020-11-13 01:57
should be fixed

**Comment by ale5000-git** [comment] 2020-11-13 19:37
@Elbullazul

Thanks, the situation improved but there are still some problems:
- When the desktop icon is selected the icon become completely black
- Maximize/Minimize/Close buttons aren't themed on Thunar and some opther place (although there are also place where it works)

**Comment by Elbullazul** [comment] 2020-11-13 20:40
> When a desktop icon is selected the icon become completely black

I think it's because the "selected view item" has a gradient as background, but it can't be rendered in this case. I'll see if adding a backgound color anyways fixes this

---
> Maximize/Minimize/Close buttons aren't themed

You have to change that theme manually in settings > Window manager settings > theme

**Comment by ale5000-git** [comment] 2020-11-13 21:37
By selecting Kokodi theme in these settings it look more similar, but how to get "Windows-7" theme in this list?

**Comment by ale5000-git** [comment] 2020-11-13 21:44
1) To see how it looks now: 
![desktop-icons](https://user-images.githubusercontent.com/15793015/99123959-87cb4300-2601-11eb-8816-2764c4f8acf7.png)
2) Enlarging text shadow may improved readbility on not seletec icons
3) Add text shadow may improve readability of selected icons

**Comment by Elbullazul** [comment] 2020-11-13 21:47
oh, I forgot this theme doesn't have a xfwm4 theme yet. Added to the todo list

**Comment by ale5000-git** [comment] 2020-11-13 21:49
I appreciate your works, thanks.

**Comment by Elbullazul** [comment] 2020-11-16 00:43
added text shadow, added Xfwm4 theme. Unfortunately, couldn't find the cause of the black icons

**Comment by Elbullazul** [comment] 2020-11-27 00:38
> 1. Also another issue:
>    ![win7-theme-icon-menu](https://user-images.githubusercontent.com/15793015/80054844-9e546480-8520-11ea-82d2-373bcf05479c.png)

Fixed in 5953623:
![image](https://user-images.githubusercontent.com/15310985/100398951-d83d9a00-301e-11eb-8678-3c1e5424bca0.png)

**Comment by ale5000-git** [comment] 2020-11-28 19:24
Thanks, most problems are fixed.
Regarding icon selection, inside a normal folder it looks fine: 
![Folder-selection](https://user-images.githubusercontent.com/15793015/100524334-998f1780-31b7-11eb-85f6-708151268234.png)

But on the desktop is bugged: 
![Desktop-selection](https://user-images.githubusercontent.com/15793015/100524340-a449ac80-31b7-11eb-8139-ca8d36af796e.png)

**Comment by Elbullazul** [comment] 2020-12-02 01:25
e67eaa8 fixes this.

Remaining issues:
- The background color of the pinned apps is darker
- Vertical white lines around some panel buttons

**Comment by Elbullazul** [comment] 2020-12-06 01:18
d8a456e fixes the launchers

**Comment by Elbullazul** [comment] 2020-12-06 02:24
4a06836 fixes the gaps around panel buttons. Couldn't manage to add in the missing shadows unfortunately, but I hope it's fixable in Xfce's next release.

**Closed by Elbullazul** 2020-12-06 02:24 UTC
